### ISSUE TITLE
关于timer的一个问题

### ISSUE THREAD

**Issue by lixiaoqing123456** [saosir/libevent-comment#1]
你好，看了你的注释对我理解代码帮助很大。但是在看的时候我有一个小问题，就是假如我注册了两个超时事件分别是2s和4s，目前系统的时间是100，也就是在102触发第一个事件104触发第二个事件。假如现在102到了触发了第一个超时事件，然后设置了tv_cache=102，但是在调用第一个事件的回调函数时花了4s，也就是实际的时间到了106。在设置第二个超时事件是，即timeout_next(base, &tv_p); 里面使用的系统时间还是102，但是实际了时间已经到106了本应该直接激活的，但是还是放在epoll_wait里面等待了2s才激活。就是这里我有点想不明白，能不能给我解答一下。谢谢！

**Comment by saosir** [comment]
你是调用第一个事件时候设置了tv_cache=102吗？这样好像会导致第二次调用timeout_next时候用tv_cache=102作为当前系统时间
